swagger: '2.0'
info:
  description: This is a restaurant website from the backend side.
  version: 1.0.0
  title: Delilah Resto
  contact:
    email: davidsv20@icloud.com
    url: https://github.com/DaveSV100/delilah-resto.git
tags:
- name: home
  description: Homepage
- name: users
  description: Users of Delilah Resto
- name: dishes
  description: Dishes from our restaurant
- name: orders
  description: Orders taken
paths:
  /users:
    get:
        tags:
        - users
        summary: List of users
        description: Returns all the users (only admins have access)
        produces:
        - application/json
        responses:
          200:
            description: successful operation
            schema:
              type: array
              items:
                $ref: '#/definitions/user'
          400:
            description: Bad request
          401: 
            description: Unauthorized
        security:
        - token:
          $ref: '#/securityDefinitions/token'
    put:
      tags:
      - users
      summary: Update an existing user
      description: If it's an admin it'll make use of the user object format but if it's a normal user it'll utilize the client_user format
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: user data
        in: body
        description: User data
        required: true
        schema:
          $ref: '#/definitions/client_user'
          $ref: '#/definitions/user'
      responses:
        200: 
          description: successful operation
            schema: 
              type: array
                items:
                  $ref: '#/definitions/ok'
        400:
          description: Bad request. Missing arguments
        404:
          description: User not found
      security:
        - token:
          $ref: '#/securityDefinitions/token'
    delete:
      tags:
      - user
      summary: Delete user
      description: A normal user can delete only his own account. Admins can insert the email of an especific account to be deleted
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Email
        required: true
        schema:
          $ref: '#/definitions/user_email'
      responses:
        200
          description: User removed
        400:
          description: Invalid data
        404:
          description: User not found
  /users/{id}:
    get:
      tags:
      - users
      summary: Gets a user by id
      description: It returns the data of a user by the id provided in the parameters. Only for admis
      produces:
      - application/json
      parameters:
      - name: id
        in: path
        description: ID of user
        required: true
        type: integer
        format: int64
      responses:
        200:
          description: successful operation
          schema:
            $ref: '#/definitions/user'
        400:
          description: Invalid ID supplied
        401:
          description: Unauthorized
        404:
          description: User not found
  /users/login:
    post:
      tags:
      - users
      summary: Logs user into the system and provides a token with a payload indicating the data of user
      produces:
      - application/json
      parameters:
      - name: user data
        in: body
        description: User data
        required: true
        schema:
          $ref: '#/definitions/user_data'
      responses:
        200:
          description: successful operation. Token signed
          schema:
            type: string
            $ref: '#definitions/Token_res'
        400:
          description: Invalid input
        404: 
          description: User not found
  /users/signup:
    post:
      tags:
      - Users
      summary: Create a new account
      parameters:
      - name: New_data
        in: body
        description: New data to sign up
        required: true
        schema:
          $ref: '#/definitions/new_user'
      responses:
        200:
            description: successful operation
            schema:
              type: string
              $ref: '#definitions/ok'
        400:
          description: Incomplete form
  /dishes:
    get:
        tags:
        - Dishes
        summary: Show list of dishes
        description: All the users have access to the products list
        produces:
        - application/json
        responses:
          200:
            description: successful operation
            schema:
              type: array
              items:
                $ref: '#/definitions/dish'
          401: 
            description: Unathorized access, you need to sign in or sign up
          404:
            description: Invalid request
        security:
        - token:
          $ref: '#/securityDefinitions/token'
    post:
      tags:
      - Dishes
      summary: Create a new dish
      description: Only admins are allowed to create a new product
      parameters:
      - name: New_dish
        in: body
        description: New dish data
        required: true
        schema:
          $ref: '#/definitions/new_dish'
      responses:
        200:
            description: successful operation
            schema:
              type: string
              $ref: '#definitions/ok'
        400:
          description: Incomplete form
        403: 
          description: Forbidden. Only admins have access
      security:
        - token:
          $ref: '#/securityDefinitions/token'
    put:
      tags:
      - Dishes
      summary: Update an existing dish
      description: Admins can modify any dish
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: new_dish
        in: body
        description: New dish object. At least it must have the description field in order to get the product that will be modified
        required: true
        schema:
          $ref: '#/definitions/new_dish'
      responses:
        200: 
          description: successful operation
            schema: 
              type: array
                items:
                  $ref: '#/definitions/ok'
        400:
          description: Bad request. Missing arguments
        403: 
          description: Forbidden. Only admins have access
        404:
          description: Dish not found
      security:
        - token:
          $ref: '#/securityDefinitions/token'
    delete:
      tags:
      - Dishes
      summary: Delete dish
      description: Administrators can delete the dishes
      produces:
      - application/json
      parameters:
      - name: description
        in: body
        description: Name of the dish in the "description" field
        required: true
        schema:
          $ref: '#/definitions/Delete_dish'
      responses:
        200
          description: successful operation
            schema: 
              type: array
                items:
                  $ref: '#/definitions/ok'
        400:
          description: Invalid data
        403: 
          description: Forbidden. Only admins have access
        404:
          description: Dish not found
      security:
        - token:
          $ref: '#/securityDefinitions/token'
  /orders:
    get:
        tags:
        - Orders
        summary: Show list of orders
        description: Admins can see all the orders and clients only their own orders.\
          \ Admins $ref => '#/definitions/orders_admin' && Clients $ref => '#/definitions/orders_client'
        produces:
        - application/json
        responses:
          200:
            description: successful operation
            schema:
              type: array
              items:
                $ref: '#/definitions/orders_admin'
                $ref: '#/definitions/orders_client'
          400:
            description: Missing arguments
          401: 
            description: Client has to sign in or sign up
          403: 
            description: Forbidden, only admins have access
          404:
            description: No orders in database
        security:
        - token:
          $ref: '#/securityDefinitions/token'
    post:
      tags:
      - Orders
      summary: Create a new dish
      description: Every user can create a new order
      parameters:
      - name: New_dish
        in: body
        description: New dish data
        required: true
        schema:
          $ref: '#/definitions/new_dish'
      responses:
        200:
            description: successful operation
            schema:
              type: string
              $ref: '#definitions/ok'
        400:
          description: Incomplete form
        403: 
          description: Forbidden. Only for admins
      security:
        - token:
          $ref: '#/securityDefinitions/token'
    put:
      tags:
      - Orders
      summary: Update an existing dish
      description: Admins can modify any dish
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: new_dish
        in: body
        description: New dish object. At least it must have the description field in order to get the product that will be modified
        required: true
        schema:
          $ref: '#/definitions/new_dish'
      responses:
        200: 
          description: successful operation
            schema: 
              type: array
                items:
                  $ref: '#/definitions/order'
        400:
          description: Bad request. Missing arguments
        403: 
          description: Forbidden. Only admins have access
        404:
          description: Dish not found
      security:
        - token:
          $ref: '#/securityDefinitions/token'
    delete:
      tags:
      - Orders
      summary: Delete dish
      description: Administrators can delete the dishes
      produces:
      - application/json
      parameters:
      - name: description
        in: body
        description: Name of the dish in the "description" field
        required: true
        schema:
          $ref: '#/definitions/Delete_dish'
      responses:
        200
          description: successful operation
            schema: 
              type: array
                items:
                  $ref: '#/definitions/ok'
        400:
          description: Invalid data
        403: 
          description: Forbidden. Only admins have access
        404:
          description: Dish not found
      security:
        - token:
          $ref: '#/securityDefinitions/token'
securityDefinitions:
  token:
    name: Bearer token
    type: Token
    in: header
    description: It must have the word "Bearer " (string) plus the token (string)
  petstore_auth:
    type: oauth2
    authorizationUrl: http://petstore.swagger.io/oauth/dialog
    flow: implicit
    scopes:
      write:pets: modify pets in your account
      read:pets: read your pets
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Token_res: 
    type: object
    properties:
      message: 
        type: string
      token: 
        type: string
  OK: 
    type: object
    properties:
      message: 
        type: string
  New_user:
    type: object
    properties:
      id:
        type: int
        format: int64
      name:
        type: string
        format: varchar255
      email:
        type: string
        format: varchar255
      password:
        type: string
        format: varchar255
      direction:
        type: string
        format: varchar255
  User:
    type: object
    properties:
      id:
        type: int
        format: int64
      name:
        type: string
        format: varchar255
      email:
        type: string
        format: varchar255
      password:
        type: string
        format: varchar255
      direction:
        type: string
        format: varchar255
      admin:
        type: integer
        format: tinyint
        default: 0
        description: Shows the role of user. Admin = 1, customer = 0
  Welcome_user:
    type: object
    properties:
      Message:
        type: string
      token:
        type: string
  User_data:
    type: object
    properties:
      email:
        type: string
        format: varchar255
      password:
        type: string
        format: varchar255
  User_email: 
    type: object
    properties: 
      email: 
        type: string
        format: varchar255
  Dish:
    type: object
    properties:
      id:
        type: integer
        format: int64
      description:
        type: string
        format: varchar255
      image:
        type: string
        format: text
      price:
        type: number
        format: int64
  New_dish:
    type: object
    properties:
      description:
        type: string
        format: varchar255
      image:
        type: string
        format: text
      price:
        type: number
        format: int64
  Delete_dish: 
    type: object
    propereties:
      description: 
        type: string
        format: varchar255
  Orders_client:
    type: object
    properties: 
      id: 
        type: number
        format: int
      status:
        type: string
        format: varchar255
        enum:
        - New
        - Confirmed
        - Preparing
        - Delivering
        - Cancelled
        - Delivered
      date: 
        type: string
        format: datetime
      description: 
        type: string
        format: varchar255
      image:
        type: string
        format: text
      price:
        type: number
        format: int
      payment: 
        type: string
        format: varchar255
      name:
        type: string
        format: varchar255
      direction: 
        type: string
        format: varchar255
  Orders_admin:
    type: object
    properties: 
      id: 
        type: number
        format: int
      status:
        type: string
        format: varchar255
        enum:
        - New
        - Confirmed
        - Preparing
        - Delivering
        - Cancelled
        - Delivered
      date: 
        type: string
        format: datetime
      description: 
        type: string
        format: varchar255
      image:
        type: string
        format: text
      price:
        type: number
        format: int
      payment: 
        type: string
        format: varchar255
      name:
        type: string
        format: varchar255
      direction: 
        type: string
        format: varchar255
      admin: 
        type: number
        format: tinyint
        description: 1 => admin && 0 => client
        enum:
        - 1
        - 0
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /dsv4/Delilah/1.0.0
schemes:
 - https
 - http